# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c7096f4640256925923a8cb24aef569cdcf494202d361dd8b26687bcf73f9ed47bda3628f9d817771f82e14f7a87e26e6865b265f53c79fa6d1c56a2a89d5af

test:
  secret_key_base: c867b07a1ccbd9acae114a1eafe0e97580d74dedcea008dfed1928b7ca19c63979078cfc2025ea596e6145c56502f3c2cfb566c3a78dfb0a4761c23ca8db8b4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
